// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Oleg-Skalozub/testtask/src/infrastructure/db (interfaces: SqlBD)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	gorm "github.com/jinzhu/gorm"
	reflect "reflect"
)

// MockSqlBD is a mock of SqlBD interface
type MockSqlBD struct {
	ctrl     *gomock.Controller
	recorder *MockSqlBDMockRecorder
}

// MockSqlBDMockRecorder is the mock recorder for MockSqlBD
type MockSqlBDMockRecorder struct {
	mock *MockSqlBD
}

// NewMockSqlBD creates a new mock instance
func NewMockSqlBD(ctrl *gomock.Controller) *MockSqlBD {
	mock := &MockSqlBD{ctrl: ctrl}
	mock.recorder = &MockSqlBDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSqlBD) EXPECT() *MockSqlBDMockRecorder {
	return m.recorder
}

// AutoMigrate mocks base method
func (m *MockSqlBD) AutoMigrate(arg0 interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoMigrate", arg0)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// AutoMigrate indicates an expected call of AutoMigrate
func (mr *MockSqlBDMockRecorder) AutoMigrate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoMigrate", reflect.TypeOf((*MockSqlBD)(nil).AutoMigrate), arg0)
}

// Close mocks base method
func (m *MockSqlBD) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockSqlBDMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSqlBD)(nil).Close))
}

// Group mocks base method
func (m *MockSqlBD) Group(arg0 string) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Group", arg0)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Group indicates an expected call of Group
func (mr *MockSqlBDMockRecorder) Group(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Group", reflect.TypeOf((*MockSqlBD)(nil).Group), arg0)
}

// Save mocks base method
func (m *MockSqlBD) Save(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save
func (mr *MockSqlBDMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSqlBD)(nil).Save), arg0)
}

// Select mocks base method
func (m *MockSqlBD) Select(arg0 interface{}, arg1 ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Select", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Select indicates an expected call of Select
func (mr *MockSqlBDMockRecorder) Select(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockSqlBD)(nil).Select), varargs...)
}

// Table mocks base method
func (m *MockSqlBD) Table(arg0 string) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Table", arg0)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Table indicates an expected call of Table
func (mr *MockSqlBDMockRecorder) Table(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Table", reflect.TypeOf((*MockSqlBD)(nil).Table), arg0)
}

// Where mocks base method
func (m *MockSqlBD) Where(arg0 interface{}, arg1 ...interface{}) *gorm.DB {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Where", varargs...)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Where indicates an expected call of Where
func (mr *MockSqlBDMockRecorder) Where(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockSqlBD)(nil).Where), varargs...)
}
